authors:
  me:
    name: Duy M. Nguyen
    description: The blog owner
    avatar: https://tryhardguides.com/wp-content/uploads/2023/05/spider-verse-portal-icon.png
  another me:
    name: Mason
    description: The blog owner
    avatar: https://tryhardguides.com/wp-content/uploads/2023/05/spider-verse-portal-icon.png